name: infrastructure-stagging

on:
  push:
    branches:
      - master
    paths: 
      - .infrastructure/stagging/**
  pull_request:
    branches:
      - master
    paths: 
      - .infrastructure/stagging/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run Terraform fmt check
        id: fmt
        run: terraform fmt -check -diff -recursive  

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: .infrastructure/stagging

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: .infrastructure/stagging

      #- name: Terraform Apply
       # id: apply
       # run: terraform apply --auto-approve
       #working-directory: .infrastructure/stagging

      - name: Terraform destroy 
        id: destroy 
        run: terraform destroy --auto-approve
        working-directory: .infrastructure/stagging