name: 'Terraform - Production'

on:
  push:
    branches:
    - master
    paths: 
    - .infrastructure/prod/**
  pull_request:
    branches:
    - master
    paths: 
    - .infrastructure/prod/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run terraform fmt check
        id: fmt
        run: terraform fmt -check -diff -recursive  

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: .infrastructure/prod

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: .infrastructure/prod

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: .infrastructure/prod
